# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "better_states_select"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Goebel", "Rick Olson", "Larry Sprock"]
  s.date = "2012-07-23"
  s.description = "Better State select Rails plugin"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION"
  ]
  s.homepage = "http://github.com/yyyc514/better-states-select"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Better State select Rails plugin"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 1.2"])
    else
      s.add_dependency(%q<rails>, [">= 1.2"])
    end
  else
    s.add_dependency(%q<rails>, [">= 1.2"])
  end
end

